use_frameworks!

target 'FormTableView_Example' do
    
#    pod 'FormTableView', :path => '.'
    pod 'FormTableView', :git => 'https://github.com/jmhdevelop/FormTableView.git'

  target 'FormTableView_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
