references:
os: osx
language: swift
osx_image: xcode10
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone x

cache: cocoapods
podfile: Example/Podfile
before_install:
 - sudo gem install activesupport -v 4.2.6
 - rvm install 2.3.1
 - rvm use 2.3.1
 - sudo gem install cocoapods
 
script:
 #- set -o pipefail
 #- xcodebuild CODE_SIGNING_REQUIRED=NO
 xctool 
 - sdk iphonesimulator
 - workspace Example/FormTableView.xcworkspace  
 - scheme FormTableView-Example 
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
 #- pod lib lint
