references:
os: osx
language: objective-c
osx_image: xcode10
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone x
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

cache: cocoapods
podfile: Example/Podfile
before_install:
 - sudo gem install activesupport -v 4.2.6
 - rvm install 2.3.1
 - rvm use 2.3.1
 - sudo gem install cocoapods
script:
 - set -o pipefail && xcodebuild -verbose 
 -workspace Example/FormTableView.xcworkspace 
 -scheme FormTableView-Example
 - pod lib lint
