os: osx
osx_image: xcode9.2
xcode_workspace: FormTableView.xcworkspace
xcode_project: FormTableView.xcodeproj
xcode_scheme: FormTableView-Example
before_install:
- sudo gem install activesupport -v 4.2.6
- rvm install 2.3.1
- rvm use 2.3.1
- sudo gem install cocoapods
script:
- xcodebuild -workspace Example/FormTableView.xcworkspace -scheme FormTableView-Example -sdk iphonesimulator

