references:
language: swift
osx_image: xcode10
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone x

cache: cocoapods
podfile: Example/Podfile
before_install:
 - sudo gem install activesupport -v 4.2.6
 - rvm install 2.3.1
 - rvm use 2.3.1
 - sudo gem install cocoapods
 
script:
 #- xcodebuild
 #- workspace Example/FormTableView.xcworkspace  
 #- scheme FormTableView-Example 
 #- sdk iphonesimulator
 # build 
 #- pod lib lint
 - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/${POD_NAME}.xcworkspace -scheme ${POD_NAME}-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
 - pod lib lint
